# Generated by Django 4.1.5 on 2023-01-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_documento_arquivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='proprietario',
            new_name='pertence',
        ),
    ]
